### ISSUE TITLE
报错 果然到了6.1.1 gradle:4.0.1

### ISSUE THREAD

**Issue by lancexin** [ttpai/Tracker#1]
* What went wrong:
Execution failed for task ':app:transformClassesWithAjxForDebug'.
> Cannot cast object 'com.android.build.gradle.internal.pipeline.TransformTask$2$1@4ff6b8d4' with class 'com.android.build.gradle.internal.pipeline.TransformTask$2$1' to class 'com.android.build.gradle.internal.pipeline.TransformTask'

**Comment by Zihao-Wu** [comment]
在project中的build.gradle 中        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10'

**Comment by Zihao-Wu** [comment]
aspectjx 升一下就好了

**Comment by Zihao-Wu** [comment]
具体看一下新的readme
