### ISSUE TITLE
viewClick事件时的应用场景疑问

### ISSUE THREAD

**Issue by snailflying** [ttpai/Tracker#2]
viewClick时，埋点时需要获取当前页面的某些数据并上传（比如网络请求的某条数据）。请问一下，我该如何获取？麻烦了

**Comment by Zihao-Wu** [comment]
因为你这属于业务逻辑，所以框架并不支持替你自动获取数据，你可以viewClick之后。subscribe回调中通过view获取activity，然后再想办法获取 数据，或者数据与view绑定起来，如setTag。
`
        Track.from(AActivity.class).viewClick(R.id.tv_text).subscribe(new OnSubscribe<View>() {
            @Override
            public void call(View view) {
                Activity activity= (Activity) view.getContext();
                //activity...
                Log.i(TAG, "AActivity.R.id.tv_text "+ view.toString());

            }
        });`
